title: Javi Velasco
email: javier.velasco86@gmail.com
url:   "http://javivelasco.com"
description: >
  I’m a software engineer living in Madrid. I feel programming as an art and I strongly believe
  in the value of well crafted software. Currently, I work on the frontend team at SocialBro
  building an awesome user experience.

# Build settings
markdown: redcarpet

# Sass settings
sass:
  sass_dir: assets/stylesheets
  style: :compressed
